/* Stage the game into public/ for deployment.

   Only what the browser actually loads ships: index.html and the modules it
   imports. The data the prompts were built from (prevalence.tsv, the CSVs,
   battig-raw.json) is build-time only and stays out of the deploy — it is
   megabytes, and no runtime code fetches it. */
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from 'node:fs';

/* lexicon.js is generated, not committed-by-hand, and the browser's answer gate
   depends on it: without it every open prompt falls back to shape-only checks
   and scoring gets more permissive than intended. Fail loudly rather than
   shipping a quietly degraded build. */
if (!existsSync('lexicon.js')) {
  console.error('ERROR: lexicon.js is missing. Run `node build-lexicon.js` first.');
  process.exit(1);
}
if (statSync('lexicon.js').mtimeMs < statSync('prevalence.tsv').mtimeMs) {
  console.error('WARNING: lexicon.js is older than prevalence.tsv — consider rebuilding it.');
}

const FILES = [
  'index.html',
  'main.js',
  'game.js',
  'norms-prompts.js',
  'prompts.js',
  'prompt-schema.js',   // the answer gate; game.js imports it
  'lexicon.js',         // generated by build-lexicon.js — the gate's word list
  'submission-log.js',  // main.js imports it; a missing file breaks the page
];

/* Clear the contents rather than the directory itself. This project lives in a
   OneDrive folder, and removing a synced directory fails with EBUSY whenever
   the sync client (or a running dev server) has a handle on it. */
mkdirSync('public', { recursive: true });
for (const entry of readdirSync('public')) {
  rmSync(`public/${entry}`, { recursive: true, force: true });
}

/* Every local module the shipped files import must itself be shipped. Adding a
   module and forgetting it here yields a blank page with a console error nobody
   sees — which nearly happened twice (prompt-schema.js, submission-log.js), so
   it is now checked rather than remembered. */
const shipped = new Set(FILES);
const missing = [];
for (const f of FILES) {
  if (!f.endsWith('.js')) continue;
  const src = readFileSync(f, 'utf8');
  for (const m of src.matchAll(/(?:^|[\s;])(?:import|export)[^'"]*?from\s*['"](\.\/[^'"]+)['"]/g)) {
    const dep = m[1].replace(/^\.\//, '');
    if (!shipped.has(dep)) missing.push(`${f} imports ./${dep}`);
  }
  for (const m of src.matchAll(/import\(\s*['"](\.\/[^'"]+)['"]\s*\)/g)) {
    const dep = m[1].replace(/^\.\//, '');
    if (!shipped.has(dep)) missing.push(`${f} dynamically imports ./${dep}`);
  }
}
if (missing.length) {
  console.error('ERROR: these imports are not in the deploy list:');
  for (const m of new Set(missing)) console.error(`  ${m}`);
  console.error('Add them to FILES in build.js.');
  process.exit(1);
}

let total = 0;
for (const f of FILES) {
  copyFileSync(f, `public/${f}`);
  const { size } = statSync(`public/${f}`);
  total += size;
  console.log(`  ${f.padEnd(18)} ${String(size).padStart(7)} bytes`);
}
console.log(`staged ${FILES.length} files, ${(total / 1024).toFixed(0)} KB -> public/`);
