/* Stage the game into public/ for deployment.

   Only what the browser actually loads ships: index.html and the modules it
   imports. The data the prompts were built from (prevalence.tsv, the CSVs,
   battig-raw.json) is build-time only and stays out of the deploy — it is
   megabytes, and no runtime code fetches it. */
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs';

/* lexicon.js is generated, not committed-by-hand, and the browser's answer gate
   depends on it: without it every open prompt falls back to shape-only checks
   and scoring gets more permissive than intended. Fail loudly rather than
   shipping a quietly degraded build. */
if (!existsSync('lexicon.js')) {
  console.error('ERROR: lexicon.js is missing. Run `node build-lexicon.js` first.');
  process.exit(1);
}
if (statSync('lexicon.js').mtimeMs < statSync('prevalence.tsv').mtimeMs) {
  console.error('WARNING: lexicon.js is older than prevalence.tsv — consider rebuilding it.');
}

const FILES = [
  'index.html',
  'main.js',
  'game.js',
  'norms-prompts.js',
  'prompts.js',
  'prompt-schema.js',   // the answer gate; game.js imports it
  'lexicon.js',         // generated by build-lexicon.js — the gate's word list
];

/* Clear the contents rather than the directory itself. This project lives in a
   OneDrive folder, and removing a synced directory fails with EBUSY whenever
   the sync client (or a running dev server) has a handle on it. */
mkdirSync('public', { recursive: true });
for (const entry of readdirSync('public')) {
  rmSync(`public/${entry}`, { recursive: true, force: true });
}

let total = 0;
for (const f of FILES) {
  copyFileSync(f, `public/${f}`);
  const { size } = statSync(`public/${f}`);
  total += size;
  console.log(`  ${f.padEnd(18)} ${String(size).padStart(7)} bytes`);
}
console.log(`staged ${FILES.length} files, ${(total / 1024).toFixed(0)} KB -> public/`);
